version: "3.8"

services:
  rproxy:
    container_name: rproxy
    image: "rproxy:latest"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    build:
      context: ../rproxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - root-page
      - cv
    #       - miam
    deploy:
      restart_policy:
        condition: any
  root-page:
    container_name: root-page
    image: "root-page:latest"
    environment:
      - PORT=8080
    build:
      context: ../root-page
    deploy:
      restart_policy:
        condition: any
  cv:
    container_name: cv
    image: "cv:latest"
    environment:
      - PORT=8082
    build:
      context: ../cv
    deploy:
      restart_policy:
        condition: any
  miam-front:
    container_name: miam-front
    image: "miam-front:latest"
    environment:
      - PORT=8081
    build:
      context: ../miam2/front
    deploy:
      restart_policy:
        condition: any
  # miam:
  #   container_name: miam
  #   image: "miam:latest"
  #   environment:
  #     - PORT=8081
  #   build:
  #     context: ../miam
  #   volumes:
  #     - /data/miamdb:/data/miamdb
  #   deploy:
  #     restart_policy:
  #       condition: any
