version: "3.8"
services:
  rproxy:
    container_name: rproxy
    image: "jallegre/rproxy:latest"
    build:
      context: ../rproxy
    ports:
      - "80:80"
    # depends_on:
    #   - miam
    #   - cv
    deploy:
      restart_policy:
        condition: any
  miam:
    container_name: miam
    image: "jallegre/miam:latest"
    environment:
      - PORT=8081
    build:
      context: ../miam
    volumes:
      - /data/miamdb:/data/miamdb
    deploy:
      restart_policy:
        condition: any
  cv:
    container_name: cv
    image: "jallegre/cv:latest"
    environment:
      - PORT=8082
    build:
      context: ../cv
    deploy:
      restart_policy:
        condition: any
