version: "3.8"

services:
  rproxy:
    container_name: rproxy
    image: "rproxy:latest"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    build:
      context: ../rproxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - root-page
      - cv
      - miam-front
      - miam-back
    deploy:
      restart_policy:
        condition: any
  root-page:
    container_name: root-page
    image: "root-page:latest"
    environment:
      - PORT=8080
    build:
      context: ../root-page
    deploy:
      restart_policy:
        condition: any
  cv:
    container_name: cv
    image: "cv:latest"
    environment:
      - PORT=8082
    build:
      context: ../cv
    deploy:
      restart_policy:
        condition: any
  miam-front:
    container_name: miam-front
    image: "miam-front:latest"
    environment:
      - PORT=8083
    build:
      context: ../miam2/ #Must be the root of the project to get shared/common files
      dockerfile: ../miam2/front.Dockerfile
    deploy:
      restart_policy:
        condition: any
  miam-back:
    container_name: miam-back
    image: "miam-back:latest"
    environment:
      - PORT=8084
    build:
      context: ../miam2/ #Must be the root of the project to get shared/common files
      dockerfile: ../miam2/back.Dockerfile
    volumes:
      - /data/miamdb:/data/miamdb
    deploy:
      restart_policy:
        condition: any
